/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design Specification Colors
        "surface": "#fdf8f7",
        "surface-dim": "#ddd9d8",
        "surface-bright": "#fdf8f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f1",
        "surface-container": "#f1edec",
        "surface-container-high": "#ece7e6",
        "surface-container-highest": "#e6e1e0",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#4d4541",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        "outline": "#7f7570",
        "outline-variant": "#d0c4be",
        "surface-tint": "#635d5a",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1f1b19",
        "on-primary-container": "#8a827f",
        "inverse-primary": "#cec5c1",
        "secondary": "#5a632e",
        "on-secondary": "#ffffff",
        "secondary-container": "#dce5a3",
        "on-secondary-container": "#5f6732",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "on-tertiary-container": "#838484",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#eae1dd",
        "primary-fixed-dim": "#cec5c1",
        "on-primary-fixed": "#1f1b19",
        "on-primary-fixed-variant": "#4b4643",
        "secondary-fixed": "#dfe8a6",
        "secondary-fixed-dim": "#c3cc8c",
        "on-secondary-fixed": "#191e00",
        "on-secondary-fixed-variant": "#434b18",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "background": "#fdf8f7",
        "on-background": "#1c1b1b",
        "surface-variant": "#e6e1e0",
        "espresso-900": "#1A1614",
        "charcoal-text": "#121212",
        "earth-olive": "#4B5320",
        
        // Cafe Shades (Extended)
        cafe: {
          50: '#F9F8F7',
          100: '#F5EFE6',
          200: '#E5E1DE',
          300: '#D5C4AC',
          400: '#B9A183',
          500: '#9E825F',
          600: '#7E6343',
          700: '#5F462D',
          800: '#3D2D1B',
          900: '#231A0F',
        },
        // Earth Shades (Extended)
        earth: {
          slate: '#475569',
          green: '#1E3F20',
          olive: '#4B5320',
          moss: '#A9B388',
        }
      },
      fontFamily: {
        sans: ['Manrope', 'var(--font-outfit)', 'Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        'full': '9999px',
      },
      spacing: {
        'touch-target-min': '48px',
        'touch-target-opt': '52px',
        'gutter': '1.5rem',
        'margin-mobile': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.08)',
        'premium': '0 10px 40px -10px rgba(61, 45, 27, 0.12)',
        'premium-lg': '0 24px 48px -12px rgba(0, 0, 0, 0.08)',
      }
    },
  },
  plugins: [],
}

